### ISSUE TITLE
Discord Reports cannot be closed

### ISSUE THREAD

**Issue by Tunnelbliick** [mirage-software/Kabooty#68]
The interaction throws an error.

**Comment by Tunnelbliick** [comment]
`C:\Users\lars1\Documents\git\Kabooty\node_modules\discord.js\src\client\actions\InteractionCreate.js:48
        if (channel && !channel.isText()) return;
                                ^

TypeError: channel.isText is not a function
    at InteractionCreateAction.handle (C:\Users\lars1\Documents\git\Kabooty\node_modules\discord.js\src\client\actions\InteractionCreate.js:48:33)
    at module.exports [as INTERACTION_CREATE] (C:\Users\lars1\Documents\git\Kabooty\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (C:\Users\lars1\Documents\git\Kabooty\node_modules\discord.js\src\client\websocket\WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (C:\Users\lars1\Documents\git\Kabooty\node_modules\discord.js\src\client\websocket\WebSocketShard.js:482:22)
    at WebSocketShard.onMessage (C:\Users\lars1\Documents\git\Kabooty\node_modules\discord.js\src\client\websocket\WebSocketShard.js:317:10)
    at WebSocket.onMessage (C:\Users\lars1\Documents\git\Kabooty\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (C:\Users\lars1\Documents\git\Kabooty\node_modules\ws\lib\websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)

Node.js v18.12.1`
